project:
  type: website
engine: julia
julia:
  exeflags: ["--project", "--threads=auto"]
execute-dir: project
bibliography: references.bib
csl: apa-annotated-bibliography.csl
github:
  owner: palday
  repo: juliacon2024
author: Phillip Alday

website:
  title: "title: BoxCox.jl -- A lightweight package with nice extensions"
  # reader-mode: true
  repo-url: https://github.com/palday/juliacon2024
  repo-actions: [edit, issue]
format:
  html:
    theme: [default, beacon.scss]
      # light: flatly
      # dark: darkly
    toc: true
    author:
      - name: Phillip Alday
        email: me@phillipalday.com
        orcid: 0000-0002-9984-5745
  revealjs:
    echo: false
  ipynb: default
