project:
  type: website
engine: julia
julia:
  exeflags: ["--project", "--threads=auto"]
execute-dir: project
bibliography: references.bib
csl: apa-annotated-bibliography.csl
github:
  owner: palday
  repo: juliacon2024
author: Phillip Alday
date: last-modified

website:
  title: "title: BoxCox.jl -- A lightweight package with nice extensions"
  # reader-mode: true
  repo-url: https://github.com/palday/juliacon2024
  repo-actions: [edit, issue]
  # cookie-consent:
  #   type: express
  #   style: headline
  #   palette: dark
#   sidebar:
#     style: "docked"
#     search: true
#     contents:
#       - href: index.qmd
#         text: Home
#       - href: 01-intro.qmd
#         text: MixedModels.jl
#       - href: 02-plotting.qmd
#         text: Visualization
#       - href: 03-extensions.qmd
#         text: Extension Packages
#       - href: 04-bootstrap.qmd
#         text: Bootstrap
#       - href: 99-wilkinson-notation.md
#         text: Formula Syntax
format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    author:
      - name: Phillip Alday
        email: me@phillipalday.com
        orcid: 0000-0002-9984-5745
  revealjs: 
    echo: false
  ipynb: default
